### PR TITLE
Update pruefungen.md

### PR DESCRIPTION
**Pull request by Wekra**
Refer to the official university download webpage to get the current SPOs.
Improve the section about calculators:
- clarify wrong content about allowed calculators for the second semester
- add hint to the possibility to borrow a calculator from the secretariat to use for an exam.

### CODE REVIEW

**Review by jwestenhoff — DISMISSED** [review]
You can use the suggestions if you like :)

**Comment by Wekra** [comment]
@jwestenhoff I included them, thank you!

**Review by milbegreif — APPROVED** [review]
IS OK

**Review by mapelpapel — APPROVED** [review]

**Review by AnjaB93 — COMMENTED** [review]
Passt ;)

**Review by SimonKienzler — APPROVED** [review]

**Pull request merged**
